import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1774695167585 implements MigrationInterface {
    name = 'InitialSchema1774695167585'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_account_status_enum" AS ENUM('active', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying, "display_name" character varying NOT NULL, "avatar_url" character varying, "email_verified_at" TIMESTAMP WITH TIME ZONE, "has_fan_role" boolean NOT NULL DEFAULT true, "is_admin" boolean NOT NULL DEFAULT false, "account_status" "public"."users_account_status_enum" NOT NULL DEFAULT 'active', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_actions_target_type_enum" AS ENUM('post', 'product', 'collection', 'user', 'creator_profile')`);
        await queryRunner.query(`CREATE TYPE "public"."moderation_actions_action_type_enum" AS ENUM('warn_user', 'restrict_creator', 'remove_content', 'dismiss_report', 'approve_creator', 'reject_creator', 'suspend_creator')`);
        await queryRunner.query(`CREATE TABLE "moderation_actions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin_user_id" uuid NOT NULL, "report_id" uuid, "target_type" "public"."moderation_actions_target_type_enum" NOT NULL, "target_id" uuid NOT NULL, "action_type" "public"."moderation_actions_action_type_enum" NOT NULL, "admin_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d259906fb4d2a5ef718f1f66e35" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reports_target_type_enum" AS ENUM('post', 'product', 'collection', 'user', 'creator_profile')`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('open', 'under_review', 'actioned', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reporter_user_id" uuid NOT NULL, "target_type" "public"."reports_target_type_enum" NOT NULL, "target_id" uuid NOT NULL, "reason_code" character varying NOT NULL, "details" text, "status" "public"."reports_status_enum" NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_notification_type_enum" AS ENUM('new_post_published', 'new_product_published', 'membership_renewal_success', 'membership_renewal_failed', 'membership_cancelled_confirmed', 'membership_expired', 'creator_application_approved', 'creator_application_rejected', 'admin_broadcast', 'order_confirmed')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient_user_id" uuid NOT NULL, "notification_type" "public"."notifications_notification_type_enum" NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "action_url" character varying, "read_at" TIMESTAMP WITH TIME ZONE, "actor_user_id" uuid, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."legal_document_versions_document_type_enum" AS ENUM('terms_of_service', 'privacy_policy', 'creator_agreement')`);
        await queryRunner.query(`CREATE TABLE "legal_document_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_type" "public"."legal_document_versions_document_type_enum" NOT NULL, "version_identifier" character varying NOT NULL, "effective_date" date NOT NULL, "is_current" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_68e43b37908d503871bfbedd366" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."consent_records_document_type_enum" AS ENUM('terms_of_service', 'privacy_policy', 'creator_agreement')`);
        await queryRunner.query(`CREATE TYPE "public"."consent_records_consent_method_enum" AS ENUM('fan_signup_email', 'fan_signup_google', 'creator_signup_email', 'creator_signup_google', 'onboarding_agreement_step')`);
        await queryRunner.query(`CREATE TABLE "consent_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "document_type" "public"."consent_records_document_type_enum" NOT NULL, "legal_document_version_id" uuid NOT NULL, "consented_at" TIMESTAMP WITH TIME ZONE NOT NULL, "consent_method" "public"."consent_records_consent_method_enum" NOT NULL, "ip_address" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_030be152eaa44998166470b2ccc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."creator_profiles_category_enum" AS ENUM('writer', 'illustrator', 'educator', 'podcaster', 'musician', 'designer', 'developer', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."creator_profiles_status_enum" AS ENUM('onboarding', 'pending_review', 'approved', 'rejected', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "creator_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "username" character varying NOT NULL, "display_name" character varying NOT NULL, "bio" text, "avatar_url" character varying, "cover_image_url" character varying, "category" "public"."creator_profiles_category_enum" NOT NULL, "content_format_tags" text array NOT NULL DEFAULT '{}', "status" "public"."creator_profiles_status_enum" NOT NULL DEFAULT 'onboarding', "onboarding_last_step" integer NOT NULL DEFAULT '0', "approved_at" TIMESTAMP WITH TIME ZONE, "suspended_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_6fae0dfbe41d4c7b37a6e3251c5" UNIQUE ("user_id"), CONSTRAINT "UQ_817b1f769b78e0bb2e577442d07" UNIQUE ("username"), CONSTRAINT "REL_6fae0dfbe41d4c7b37a6e3251c" UNIQUE ("user_id"), CONSTRAINT "PK_5f58900809b867a2683b6e0e94a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."membership_plans_status_enum" AS ENUM('draft', 'published', 'hidden', 'archived')`);
        await queryRunner.query(`CREATE TABLE "membership_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "price_monthly_try" integer NOT NULL, "price_annual_try" integer, "currency" character varying NOT NULL DEFAULT 'TRY', "tier_rank" integer NOT NULL, "perks" jsonb NOT NULL DEFAULT '[]', "status" "public"."membership_plans_status_enum" NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_85ca9d6f4262a6bbff2a540c640" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."creator_applications_decision_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "creator_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by_admin_id" uuid, "decision" "public"."creator_applications_decision_enum" NOT NULL DEFAULT 'pending', "rejection_reason" text, "iban_encrypted" character varying NOT NULL, "iban_format_valid" boolean NOT NULL, "iban_last_four" character varying(4), "agreement_version_id" uuid NOT NULL, "agreement_accepted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "resubmission_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d1b7eb7218323d0fd1de08c70c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_publish_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."products_moderation_status_enum" AS ENUM('clean', 'flagged', 'removed')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "price_try" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'TRY', "publish_status" "public"."products_publish_status_enum" NOT NULL DEFAULT 'draft', "moderation_status" "public"."products_moderation_status_enum" NOT NULL DEFAULT 'clean', "file_storage_key" character varying NOT NULL, "preview_file_storage_key" character varying, "original_filename" character varying NOT NULL, "file_size_bytes" bigint NOT NULL, "content_type" character varying NOT NULL, "flagged_at" TIMESTAMP WITH TIME ZONE, "removed_at" TIMESTAMP WITH TIME ZONE, "moderation_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "storage_key" character varying NOT NULL, "original_filename" character varying NOT NULL, "file_size_bytes" bigint NOT NULL, "content_type" character varying NOT NULL, "is_downloadable" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_791a1c9044e40ac5c37aab661f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."posts_publish_status_enum" AS ENUM('draft', 'published', 'scheduled', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."posts_moderation_status_enum" AS ENUM('clean', 'flagged', 'removed')`);
        await queryRunner.query(`CREATE TYPE "public"."posts_access_level_enum" AS ENUM('public', 'member_only', 'tier_gated', 'premium')`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "title" character varying NOT NULL, "content" jsonb, "publish_status" "public"."posts_publish_status_enum" NOT NULL DEFAULT 'draft', "moderation_status" "public"."posts_moderation_status_enum" NOT NULL DEFAULT 'clean', "access_level" "public"."posts_access_level_enum" NOT NULL DEFAULT 'public', "required_tier_id" uuid, "price_try" integer, "published_at" TIMESTAMP WITH TIME ZONE, "scheduled_at" TIMESTAMP WITH TIME ZONE, "flagged_at" TIMESTAMP WITH TIME ZONE, "removed_at" TIMESTAMP WITH TIME ZONE, "moderation_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."collection_items_item_type_enum" AS ENUM('post', 'product')`);
        await queryRunner.query(`CREATE TABLE "collection_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "collection_id" uuid NOT NULL, "item_type" "public"."collection_items_item_type_enum" NOT NULL, "item_id" uuid NOT NULL, "sort_order" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5f299da96958a920ab58871ea57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."collections_access_type_enum" AS ENUM('purchase', 'tier_gated')`);
        await queryRunner.query(`CREATE TYPE "public"."collections_publish_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."collections_moderation_status_enum" AS ENUM('clean', 'flagged', 'removed')`);
        await queryRunner.query(`CREATE TABLE "collections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "creator_profile_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "access_type" "public"."collections_access_type_enum" NOT NULL, "price_try" integer, "required_tier_id" uuid, "publish_status" "public"."collections_publish_status_enum" NOT NULL DEFAULT 'draft', "moderation_status" "public"."collections_moderation_status_enum" NOT NULL DEFAULT 'clean', "item_count" integer NOT NULL DEFAULT '0', "flagged_at" TIMESTAMP WITH TIME ZONE, "removed_at" TIMESTAMP WITH TIME ZONE, "moderation_note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_21c00b1ebbd41ba1354242c5c4e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_order_type_enum" AS ENUM('membership_checkout', 'product_purchase', 'collection_purchase', 'premium_post_purchase')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fan_user_id" uuid NOT NULL, "order_type" "public"."orders_order_type_enum" NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "amount_try" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'TRY', "gateway_transaction_id" character varying, "reference_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fan_user_id" uuid NOT NULL, "product_id" uuid NOT NULL, "order_id" uuid NOT NULL, "amount_paid_try" integer NOT NULL, "purchased_at" TIMESTAMP WITH TIME ZONE NOT NULL, "access_revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f28cf8bf29b23ab794dfc91f45c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "post_purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fan_user_id" uuid NOT NULL, "post_id" uuid NOT NULL, "order_id" uuid NOT NULL, "amount_paid_try" integer NOT NULL, "purchased_at" TIMESTAMP WITH TIME ZONE NOT NULL, "access_revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_770eb2f128e86366008ef4aa774" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "billing_customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "gateway_customer_id" character varying NOT NULL, "gateway_provider" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9247f7fb18111a77f9d5ff06b99" UNIQUE ("user_id"), CONSTRAINT "REL_9247f7fb18111a77f9d5ff06b9" UNIQUE ("user_id"), CONSTRAINT "PK_33443c37051e342361f61a54b86" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_method_summaries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "billing_customer_id" uuid NOT NULL, "gateway_payment_method_id" character varying NOT NULL, "card_brand" character varying NOT NULL, "last_four" character varying(4) NOT NULL, "expiry_month" integer NOT NULL, "expiry_year" integer NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9840707c24f0b3ca9d96e44ad41" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_invoice_type_enum" AS ENUM('subscription_charge', 'subscription_renewal', 'one_time_purchase', 'refund')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('paid', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fan_user_id" uuid NOT NULL, "membership_subscription_id" uuid, "order_id" uuid, "invoice_type" "public"."invoices_invoice_type_enum" NOT NULL, "amount_try" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'TRY', "status" "public"."invoices_status_enum" NOT NULL, "gateway_invoice_id" character varying, "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."membership_subscriptions_billing_interval_enum" AS ENUM('monthly', 'annual')`);
        await queryRunner.query(`CREATE TYPE "public"."membership_subscriptions_status_enum" AS ENUM('pending', 'active', 'cancelled', 'grace_period', 'expired')`);
        await queryRunner.query(`CREATE TABLE "membership_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fan_user_id" uuid NOT NULL, "membership_plan_id" uuid NOT NULL, "creator_profile_id" uuid NOT NULL, "billing_interval" "public"."membership_subscriptions_billing_interval_enum" NOT NULL, "status" "public"."membership_subscriptions_status_enum" NOT NULL DEFAULT 'pending', "current_period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "current_period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancellation_reason" text, "grace_period_ends_at" TIMESTAMP WITH TIME ZONE, "gateway_subscription_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d847e5098bab1df6efa300d9f1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "collection_purchases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fan_user_id" uuid NOT NULL, "collection_id" uuid NOT NULL, "order_id" uuid NOT NULL, "amount_paid_try" integer NOT NULL, "purchased_at" TIMESTAMP WITH TIME ZONE NOT NULL, "access_revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8dff66aa2f1bd5fd2e6c4fc7cc8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."oauth_accounts_provider_enum" AS ENUM('google')`);
        await queryRunner.query(`CREATE TABLE "oauth_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" "public"."oauth_accounts_provider_enum" NOT NULL, "provider_account_id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f1daab3d50d1ce730369c01c57f" UNIQUE ("provider", "provider_account_id"), CONSTRAINT "PK_710a81523f515b78f894e33bb10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "email_verification_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_417a095bbed21c2369a6a01ab9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "moderation_actions" ADD CONSTRAINT "FK_cd13aa4a13acd2592c09e22d808" FOREIGN KEY ("admin_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation_actions" ADD CONSTRAINT "FK_8dd6d136a903e4f003d61123c76" FOREIGN KEY ("report_id") REFERENCES "reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_76e1f2905a90423e477b38516e7" FOREIGN KEY ("reporter_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_2726bde496d82b6401532ab1477" FOREIGN KEY ("recipient_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "FK_b823aad0deceda10806be9aa447" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consent_records" ADD CONSTRAINT "FK_ac1220089a8ac6a594d78376dbc" FOREIGN KEY ("legal_document_version_id") REFERENCES "legal_document_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creator_profiles" ADD CONSTRAINT "FK_6fae0dfbe41d4c7b37a6e3251c5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_plans" ADD CONSTRAINT "FK_eae1ae571cf41f181efdc2e7ce9" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creator_applications" ADD CONSTRAINT "FK_549e8831d8bba797391d7d519c1" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "creator_applications" ADD CONSTRAINT "FK_a65175993fc2404c311e2b435f0" FOREIGN KEY ("agreement_version_id") REFERENCES "legal_document_versions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_f89f0928f089af2cd5acf3fff91" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_attachments" ADD CONSTRAINT "FK_4423ea1009e33b8a0a39a8b05af" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_e7c2e3a78784a387a28127e3b89" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c3870d4b0f6d95b89ad20ba1103" FOREIGN KEY ("required_tier_id") REFERENCES "membership_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_items" ADD CONSTRAINT "FK_21bf61f8ce7e69b7bcaee625676" FOREIGN KEY ("collection_id") REFERENCES "collections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collections" ADD CONSTRAINT "FK_b6c19b9176f3b30e4e5091eb41c" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collections" ADD CONSTRAINT "FK_6179a288a4bb4638a3d49bde8a0" FOREIGN KEY ("required_tier_id") REFERENCES "membership_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_8f8bdbe71dccad4465a8f6f015b" FOREIGN KEY ("fan_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_purchases" ADD CONSTRAINT "FK_4819e5396966e244db02185b4d3" FOREIGN KEY ("fan_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_purchases" ADD CONSTRAINT "FK_20b439e0af1363a6a3f162fd6d0" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_purchases" ADD CONSTRAINT "FK_8732c64887ef46fd20296bf7738" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_purchases" ADD CONSTRAINT "FK_790c62d9d414e1960e900cdc6e1" FOREIGN KEY ("fan_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_purchases" ADD CONSTRAINT "FK_446dc5f972ef940095e42327163" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_purchases" ADD CONSTRAINT "FK_d18be0c2287ce13315f31576f50" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_customers" ADD CONSTRAINT "FK_9247f7fb18111a77f9d5ff06b99" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_method_summaries" ADD CONSTRAINT "FK_1d39cacadd93b64fc6d01f4653c" FOREIGN KEY ("billing_customer_id") REFERENCES "billing_customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_7c32e839c4a6a6569877def1290" FOREIGN KEY ("fan_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_bd41f1895bf5dac2ba2dbe5b12e" FOREIGN KEY ("membership_subscription_id") REFERENCES "membership_subscriptions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ea83c3b911906a3578de2340fdf" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_subscriptions" ADD CONSTRAINT "FK_67426b412c803e3f5f1aaa4f04d" FOREIGN KEY ("fan_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_subscriptions" ADD CONSTRAINT "FK_5ba3e3591f7de68ea696930ffa2" FOREIGN KEY ("membership_plan_id") REFERENCES "membership_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "membership_subscriptions" ADD CONSTRAINT "FK_ba8491ef7de999a241b3034cb0e" FOREIGN KEY ("creator_profile_id") REFERENCES "creator_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_purchases" ADD CONSTRAINT "FK_d38eb2e690804e57020d8d99082" FOREIGN KEY ("fan_user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_purchases" ADD CONSTRAINT "FK_504b3f9e32cfc34b1d33a68e6ce" FOREIGN KEY ("collection_id") REFERENCES "collections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_purchases" ADD CONSTRAINT "FK_01c921564f6e7531949209b4fa3" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" ADD CONSTRAINT "FK_22a05e92f51a983475f9281d3b0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" ADD CONSTRAINT "FK_fdcb77f72f529bf65c95d72a147" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "email_verification_tokens" DROP CONSTRAINT "FK_fdcb77f72f529bf65c95d72a147"`);
        await queryRunner.query(`ALTER TABLE "oauth_accounts" DROP CONSTRAINT "FK_22a05e92f51a983475f9281d3b0"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "collection_purchases" DROP CONSTRAINT "FK_01c921564f6e7531949209b4fa3"`);
        await queryRunner.query(`ALTER TABLE "collection_purchases" DROP CONSTRAINT "FK_504b3f9e32cfc34b1d33a68e6ce"`);
        await queryRunner.query(`ALTER TABLE "collection_purchases" DROP CONSTRAINT "FK_d38eb2e690804e57020d8d99082"`);
        await queryRunner.query(`ALTER TABLE "membership_subscriptions" DROP CONSTRAINT "FK_ba8491ef7de999a241b3034cb0e"`);
        await queryRunner.query(`ALTER TABLE "membership_subscriptions" DROP CONSTRAINT "FK_5ba3e3591f7de68ea696930ffa2"`);
        await queryRunner.query(`ALTER TABLE "membership_subscriptions" DROP CONSTRAINT "FK_67426b412c803e3f5f1aaa4f04d"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ea83c3b911906a3578de2340fdf"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_bd41f1895bf5dac2ba2dbe5b12e"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_7c32e839c4a6a6569877def1290"`);
        await queryRunner.query(`ALTER TABLE "payment_method_summaries" DROP CONSTRAINT "FK_1d39cacadd93b64fc6d01f4653c"`);
        await queryRunner.query(`ALTER TABLE "billing_customers" DROP CONSTRAINT "FK_9247f7fb18111a77f9d5ff06b99"`);
        await queryRunner.query(`ALTER TABLE "post_purchases" DROP CONSTRAINT "FK_d18be0c2287ce13315f31576f50"`);
        await queryRunner.query(`ALTER TABLE "post_purchases" DROP CONSTRAINT "FK_446dc5f972ef940095e42327163"`);
        await queryRunner.query(`ALTER TABLE "post_purchases" DROP CONSTRAINT "FK_790c62d9d414e1960e900cdc6e1"`);
        await queryRunner.query(`ALTER TABLE "product_purchases" DROP CONSTRAINT "FK_8732c64887ef46fd20296bf7738"`);
        await queryRunner.query(`ALTER TABLE "product_purchases" DROP CONSTRAINT "FK_20b439e0af1363a6a3f162fd6d0"`);
        await queryRunner.query(`ALTER TABLE "product_purchases" DROP CONSTRAINT "FK_4819e5396966e244db02185b4d3"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_8f8bdbe71dccad4465a8f6f015b"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP CONSTRAINT "FK_6179a288a4bb4638a3d49bde8a0"`);
        await queryRunner.query(`ALTER TABLE "collections" DROP CONSTRAINT "FK_b6c19b9176f3b30e4e5091eb41c"`);
        await queryRunner.query(`ALTER TABLE "collection_items" DROP CONSTRAINT "FK_21bf61f8ce7e69b7bcaee625676"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c3870d4b0f6d95b89ad20ba1103"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_e7c2e3a78784a387a28127e3b89"`);
        await queryRunner.query(`ALTER TABLE "post_attachments" DROP CONSTRAINT "FK_4423ea1009e33b8a0a39a8b05af"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_f89f0928f089af2cd5acf3fff91"`);
        await queryRunner.query(`ALTER TABLE "creator_applications" DROP CONSTRAINT "FK_a65175993fc2404c311e2b435f0"`);
        await queryRunner.query(`ALTER TABLE "creator_applications" DROP CONSTRAINT "FK_549e8831d8bba797391d7d519c1"`);
        await queryRunner.query(`ALTER TABLE "membership_plans" DROP CONSTRAINT "FK_eae1ae571cf41f181efdc2e7ce9"`);
        await queryRunner.query(`ALTER TABLE "creator_profiles" DROP CONSTRAINT "FK_6fae0dfbe41d4c7b37a6e3251c5"`);
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "FK_ac1220089a8ac6a594d78376dbc"`);
        await queryRunner.query(`ALTER TABLE "consent_records" DROP CONSTRAINT "FK_b823aad0deceda10806be9aa447"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_2726bde496d82b6401532ab1477"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_76e1f2905a90423e477b38516e7"`);
        await queryRunner.query(`ALTER TABLE "moderation_actions" DROP CONSTRAINT "FK_8dd6d136a903e4f003d61123c76"`);
        await queryRunner.query(`ALTER TABLE "moderation_actions" DROP CONSTRAINT "FK_cd13aa4a13acd2592c09e22d808"`);
        await queryRunner.query(`DROP TABLE "email_verification_tokens"`);
        await queryRunner.query(`DROP TABLE "oauth_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."oauth_accounts_provider_enum"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "collection_purchases"`);
        await queryRunner.query(`DROP TABLE "membership_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."membership_subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."membership_subscriptions_billing_interval_enum"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_invoice_type_enum"`);
        await queryRunner.query(`DROP TABLE "payment_method_summaries"`);
        await queryRunner.query(`DROP TABLE "billing_customers"`);
        await queryRunner.query(`DROP TABLE "post_purchases"`);
        await queryRunner.query(`DROP TABLE "product_purchases"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_order_type_enum"`);
        await queryRunner.query(`DROP TABLE "collections"`);
        await queryRunner.query(`DROP TYPE "public"."collections_moderation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."collections_publish_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."collections_access_type_enum"`);
        await queryRunner.query(`DROP TABLE "collection_items"`);
        await queryRunner.query(`DROP TYPE "public"."collection_items_item_type_enum"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TYPE "public"."posts_access_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."posts_moderation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."posts_publish_status_enum"`);
        await queryRunner.query(`DROP TABLE "post_attachments"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_moderation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_publish_status_enum"`);
        await queryRunner.query(`DROP TABLE "creator_applications"`);
        await queryRunner.query(`DROP TYPE "public"."creator_applications_decision_enum"`);
        await queryRunner.query(`DROP TABLE "membership_plans"`);
        await queryRunner.query(`DROP TYPE "public"."membership_plans_status_enum"`);
        await queryRunner.query(`DROP TABLE "creator_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."creator_profiles_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."creator_profiles_category_enum"`);
        await queryRunner.query(`DROP TABLE "consent_records"`);
        await queryRunner.query(`DROP TYPE "public"."consent_records_consent_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."consent_records_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "legal_document_versions"`);
        await queryRunner.query(`DROP TYPE "public"."legal_document_versions_document_type_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."reports_target_type_enum"`);
        await queryRunner.query(`DROP TABLE "moderation_actions"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_actions_action_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."moderation_actions_target_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_account_status_enum"`);
    }

}
